//! Default abstract syntaxes accepted by the SCP, grouped by dcm4che context.

pub use crate::sop_classes::{
    SopClassContext, ALL_SOP_CLASS_UIDS, C_STORE_SOP_CLASS_UIDS, DISPLAY_SOP_CLASS_UIDS,
    LOGGING_SOP_CLASS_UIDS, MEDIA_CREATION_SOP_CLASS_UIDS,
    MEDIA_STORAGE_DIRECTORY_SOP_CLASS_UIDS, MPPS_SOP_CLASS_UIDS, OTHER_SOP_CLASS_UIDS,
    PRINT_SOP_CLASS_UIDS, PRIVATE_SOP_CLASS_UIDS, QUERY_FIND_SOP_CLASS_UIDS,
    QUERY_GET_SOP_CLASS_UIDS, QUERY_MOVE_SOP_CLASS_UIDS, STORAGE_COMMITMENT_SOP_CLASS_UIDS,
    STORAGE_SOP_CLASS_UIDS, VERIFICATION_SOP_CLASS_UIDS, WORKFLOW_SOP_CLASS_UIDS,
    WORKLIST_SOP_CLASS_UIDS,
};

/// Storage SOP classes for C-STORE SCP negotiation and routing.
pub static STORAGE_ABSTRACT_SYNTAXES: &[&str] = C_STORE_SOP_CLASS_UIDS;

/// Default SCP storage capabilities (excludes verification; added separately).
pub static ABSTRACT_SYNTAXES: &[&str] = C_STORE_SOP_CLASS_UIDS;
