name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dicom-rs-net
        uses: actions/checkout@v5
        with:
          path: dicom-rs-net

      - name: Checkout dicom-rs
        uses: actions/checkout@v5
        with:
          repository: Enet4/dicom-rs
          path: dicom-rs

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: cargo fmt
        working-directory: dicom-rs-net
        run: cargo fmt --check

      - name: cargo clippy
        working-directory: dicom-rs-net
        run: cargo clippy --all-features -- -D warnings

      - name: cargo test
        working-directory: dicom-rs-net
        run: cargo test --all-features
